Adapt README, CircleCI config and GitHub Release workflow from CAPA fork (#115)

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -1,126 +1,60 @@
-name: Create Release
+# As opposed to https://github.com/kubernetes-sigs/cluster-api (CAPI), the CAPZ upstream project does not offer
+# a GitHub action to unconditionally create releases from tags (as of 2025-10-17). Therefore, this is a Giant Swarm
+# fork-specific addition. We require a GitHub release containing the YAML manifests which we use in
+# cluster-api-provider-azure-app. Since doing this manually is very error-prone (see
+# `docs/book/src/development/releasing.md`), we run the needed commands here.
+
+name: release
 
 on:
   push:
-    branches:
-      - main
-    paths:
-      - 'CHANGELOG/*.md'
+    tags:
+      - 'v*'
 
-permissions:  # added using https://github.com/step-security/secure-repo
-  contents: read
+permissions:
+  contents: write # allow creating a release
 
 jobs:
-  push_release_tag:
-    permissions:
-      pull-requests: read  # for tj-actions/changed-files
-      contents: write  # for "Create Release Tag" step
+  build:
+    name: Create draft release
     runs-on: ubuntu-latest
-    outputs:
-      release_tag: ${{ steps.release-version.outputs.release_version }}
+    env:
+      GH_ORG_NAME: giantswarm
     steps:
-      - name: Harden Runner
-        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
-        with:
-          egress-policy: audit
-      - name: Checkout code
-        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # tag=v5.0.0
-        with:
-          fetch-depth: 0
-      - name: Get changed files
-        id: changed-markdown-files
-        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # tag=v47.0.0
-        with:
-          files: CHANGELOG/**.md
-      - name: Get release version
-        id: release-version
+      - name: Set env
         run: |
-            if [[ ${{ steps.changed-markdown-files.outputs.all_changed_files_count }} != 1 ]]; then
-              echo "1 release notes file should be changed to create a release tag, found ${{ steps.changed-markdown-files.outputs.all_changed_files_count }}"
-              exit 1
-            fi
-            for changed_file in ${{ steps.changed-markdown-files.outputs.all_changed_files }}; do
-              export RELEASE_VERSION=$(echo "${changed_file}" | grep -oP '(?<=/)[^/]+(?=\.md)')
-              echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
-              echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_OUTPUT
-              if [[ "$RELEASE_VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$ ]]; then
-                echo "Valid semver: $RELEASE_VERSION"
-              else
-                echo "Invalid semver: $RELEASE_VERSION"
-                exit 1
-              fi
-            done
-      - name: Determine the release branch to use
-        run: |
-            if [[ $RELEASE_VERSION =~ beta ]] || [[ $RELEASE_VERSION =~ alpha ]]; then
-              export RELEASE_BRANCH=main
-              echo "RELEASE_BRANCH=$RELEASE_BRANCH" >> $GITHUB_ENV
-              echo "This is a beta or alpha release, will use release branch $RELEASE_BRANCH"
-            else
-              export RELEASE_BRANCH=release-$(echo $RELEASE_VERSION | sed -E 's/^v([0-9]+)\.([0-9]+)\..*$/\1.\2/')
-              echo "RELEASE_BRANCH=$RELEASE_BRANCH" >> $GITHUB_ENV
-              echo "This is not a beta or alpha release, will use release branch $RELEASE_BRANCH"
-            fi
-      - name: Create or checkout release branch
-        run: |
-          if git show-ref --verify --quiet "refs/remotes/origin/$RELEASE_BRANCH"; then
-            echo "Branch $RELEASE_BRANCH already exists"
-            git checkout "$RELEASE_BRANCH"
-          else
-            git checkout -b "$RELEASE_BRANCH"
-            git push origin "$RELEASE_BRANCH"
-            echo "Created branch $RELEASE_BRANCH"
-          fi
-      - name: Validate tag does not already exist
-        run: |
-          if [[ $(git tag -l $RELEASE_VERSION) ]]; then
-            echo "Tag $RELEASE_VERSION already exists, exiting"
+          if echo "${GITHUB_REF}" | grep -qF "vX.Y"; then
+            >&2 echo "ERROR: Oops, you copy-pasted verbatim from the README.md - please ensure to replace 'vX.Y.Z' with an actual tag"
             exit 1
           fi
-      - name: Create Release Tag
-        run: |
-          git config user.name "${GITHUB_ACTOR}"
-          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
-          git tag -a ${RELEASE_VERSION} -m ${RELEASE_VERSION}
-          git push origin ${RELEASE_VERSION}
-          echo "Created tag $RELEASE_VERSION"
-  release:
-    permissions:
-      contents: write  # for softprops/action-gh-release to create GitHub release
-    name: create draft release
-    runs-on: ubuntu-latest
-    needs: push_release_tag
-    steps:
-      - name: Harden Runner
-        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
-        with:
-          egress-policy: audit
-      - name: Set env
-        run:  echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV
-        env:
-          RELEASE_TAG: ${{needs.push_release_tag.outputs.release_tag}}
+
+          echo "RELEASE_TAG=${GITHUB_REF:10}" >> $GITHUB_ENV # strip off `refs/tags/` prefix
+
       - name: checkout code
-        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # tag=v5.0.0
+        uses: actions/checkout@v4
         with:
           fetch-depth: 0
-          ref: ${{ env.RELEASE_TAG }}
-      - name: Get Go version
-        run: echo "go_version=$(make go-version)" >> $GITHUB_ENV
+
       - name: Set up Go
-        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # tag=v6.0.0
+        uses: actions/setup-go@v5
         with:
-          go-version: ${{ env.go_version }}
-      - name: generate release artifacts
+          go-version: '1.22'
+          cache-dependency-path: |
+            ./go.sum
+            ./hack/tools/go.sum
+
+      - name: Generate release artifacts
+        env:
+          GITHUB_TOKEN: "unused" # since we create the release without using CAPZ's Makefile target
         run: |
-          make release
-      - name: get release notes
-        run: |
-          curl -L "https://raw.githubusercontent.com/${{ github.repository }}/main/CHANGELOG/${{ env.RELEASE_TAG }}.md" \
-          -o "${{ env.RELEASE_TAG }}.md"
+          make REGISTRY="registry.k8s.io/cluster-api-aws" RELEASE_TAG="${RELEASE_TAG}" release-manifests
+
+      # Instead of `make VERSION="${RELEASE_TAG}" create-gh-release upload-gh-artifacts`, which requires GitHub CLI
+      # authentication, use an action which does the same.
       - name: Release
-        uses: softprops/action-gh-release@62c96d0c4e8a889135c1f3a25910db8dbe0e85f7 # tag=v2.3.4
+        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # tag=v1
         with:
           draft: true
           files: out/*
-          body_path: ${{ env.RELEASE_TAG }}.md
-          tag_name: ${{ env.RELEASE_TAG }}
+          body: "This fork does not provide release changelogs."
+          # `name` not needed since this takes the tag by default (which we also use above as ${RELEASE_TAG})
